// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqgdfbdgcxpxphluanln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZ2RmYmRnY3hweHBobHVhbmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjQyMDQsImV4cCI6MjA1ODg0MDIwNH0.c1E56lHypub2gjBR9XHmWJjI14zcuvihlOpJ5zFjShI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);